name: Pull Request on Branch Push
on: push

jobs:
  auto-pull-request:
    name: Automated Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: eonx-com/actions-pull-request@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "master"
          BRANCH_PREFIX: "RELEASE/"
          PULL_REQUEST_BODY: "use-commit-message"
